import streamlit as st
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain.schema import SystemMessage, HumanMessage

# Load environment variables
load_dotenv()

# Initialize LLM
llm = ChatOpenAI(
    model_name="gpt-4o-mini",
    temperature=0
)

def get_llm_response(user_input: str, expert_type: str) -> str:
    """
    Generate a response from the LLM based on user input and expert type.

    Args:
        user_input (str): The question or input text from the user.
        expert_type (str): The selected expert type (e.g., "Hypertension Expert" or "Sleep Expert").

    Returns:
        str: The response generated by the LLM.
    """
    # Define system messages based on expert type
    if expert_type == "Hypertension Expert":
        system_message = "You are an expert in hypertension. Provide detailed and accurate information about hypertension."
    elif expert_type == "Sleep Expert":
        system_message = "You are an expert in sleep science. Provide detailed and accurate information about sleep."
    else:
        system_message = "You are a helpful assistant."

    # Create messages
    messages = [
        SystemMessage(content=system_message),
        HumanMessage(content=user_input)
    ]

    # Get response from LLM
    result = llm(messages)
    return result.content

# Streamlit UI
st.title("LLM Expert Selector")

# App description
st.write("""
### App Overview
This application allows you to interact with a Language Model (LLM) as if it were a domain-specific expert. 
You can choose between two types of experts:

1. **Hypertension Expert**: Specialized in providing detailed and accurate information about hypertension.
2. **Sleep Expert**: Specialized in providing detailed and accurate information about sleep science.

### How to Use
1. Select the type of expert using the radio buttons.
2. Enter your question in the text input field.
3. View the expert's response below.
""")

# Radio button for expert selection
expert_type = st.radio(
    "Choose the type of expert:",
    ("Hypertension Expert", "Sleep Expert")
)

# User input
user_input = st.text_input("Ask a question:")

if user_input:
    # Get response from the LLM function
    response = get_llm_response(user_input, expert_type)

    # Display the result
    st.write("### Response:")
    st.write(response)